#! /usr/bin/awk -f
BEGIN{
}
!/^#/{
	cedula=$1
	suma1=0
	suma2=0
	for ( i =1 ; i < 10; i+=2 ){
		x = substr(cedula, i, 1) * 2
		if (x < 10){
			suma1 += x
		}else{
			x = x - 9 
			suma1 += x
		}	
	} 
	for ( j = 2; j < 10; j+=2 ){
		y = substr(cedula, j, 1)
		suma2 += y
	} 
	
	suma = suma1 + suma2
	nsuma = substr(suma, 2, 1)
	nfinal = substr(cedula, 10,1)
	if (nfinal != 0){
		nsuma = 10 - nsuma	
	}
	if (nfinal == nsuma){
		printf("1")
	}else{
		printf("0")
	}

}
